# Generated by Django 5.2.8 on 2025-11-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Heritage Realty & Custom Homes', help_text='Displayed in browser titles and meta where needed.', max_length=200)),
                ('primary_phone', models.CharField(blank=True, help_text='Main phone number (for header / CTA). Example: 555-123-4567', max_length=32)),
                ('primary_phone_link', models.CharField(blank=True, help_text='Phone in tel: format. Example: 15551234567', max_length=32)),
                ('primary_email', models.EmailField(blank=True, help_text='Main contact email shown publicly (if desired).', max_length=254)),
                ('hero_headline', models.CharField(blank=True, help_text='Homepage hero headline.', max_length=200)),
                ('hero_subheadline', models.TextField(blank=True, help_text='Homepage hero supporting text.')),
                ('cta_heading', models.CharField(blank=True, help_text="CTA strip heading. Example: 'Ready to get started?'", max_length=200)),
                ('cta_body', models.TextField(blank=True, help_text='CTA strip short paragraph under the heading.')),
                ('cta_phone_label', models.CharField(blank=True, help_text="Label for the phone button. Example: 'Call Us'", max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
