# Generated by Django 5.2.8 on 2026-03-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short label for the announcement (internal or small heading).', max_length=200)),
                ('message', models.TextField(help_text='Main announcement text shown in the bar.')),
                ('button_label', models.CharField(blank=True, help_text="Optional button label. Example: 'Learn More' or 'View Details'.", max_length=100)),
                ('button_url', models.URLField(blank=True, help_text='Optional URL for the button. Can be an internal or external link.')),
                ('is_active', models.BooleanField(default=False, help_text='If checked, this announcement may be shown on the site.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn page URL')),
                ('tiktok_url', models.URLField(blank=True, help_text='TikTok profile URL')),
                ('site_name', models.CharField(default='Heritage Realty & Custom Homes', help_text='Displayed in browser titles and meta where needed.', max_length=200)),
                ('primary_phone', models.CharField(blank=True, help_text='Main phone number (for header / CTA). Example: 508-555-1234', max_length=32)),
                ('primary_phone_link', models.CharField(blank=True, help_text='Phone in tel: format. Example: 15085551234', max_length=32)),
                ('primary_email', models.EmailField(blank=True, help_text='Main contact email shown publicly (if desired).', max_length=254)),
                ('lead_recipients', models.TextField(blank=True, help_text='One or more email addresses to receive website leads. Separate multiple addresses with commas or new lines.')),
                ('address_line1', models.CharField(blank=True, help_text='Office street address line 1.', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Office street address line 2 (optional).', max_length=255)),
                ('city', models.CharField(blank=True, help_text='Office city.', max_length=100)),
                ('state', models.CharField(blank=True, help_text='Office state.', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Office ZIP / postal code.', max_length=20)),
                ('hero_background', models.ImageField(blank=True, help_text='Homepage hero background image.', null=True, upload_to='site/hero/')),
                ('hero_headline', models.CharField(blank=True, help_text='Homepage hero headline.', max_length=200)),
                ('hero_subheadline', models.TextField(blank=True, help_text='Homepage hero supporting text.')),
                ('cta_heading', models.CharField(blank=True, help_text="CTA strip heading. Example: 'Ready to get started?'", max_length=200)),
                ('cta_body', models.TextField(blank=True, help_text='CTA strip short paragraph under the heading.')),
                ('cta_phone_label', models.CharField(blank=True, help_text="Label for the phone button. Example: 'Call Us'", max_length=50)),
                ('communities_intro', models.TextField(blank=True, help_text='Intro text shown at the top of the Communities page.')),
                ('plans_intro', models.TextField(blank=True, help_text='Intro text shown at the top of the Floor Plans page.')),
                ('homes_intro', models.TextField(blank=True, help_text='Intro text shown at the top of the Available Homes page.')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
