# Generated by Django 5.2.8 on 2025-11-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='lead_recipients',
            field=models.TextField(blank=True, help_text='One or more email addresses to receive website leads. Separate multiple addresses with commas or new lines.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_phone',
            field=models.CharField(blank=True, help_text='Main phone number (for header / CTA). Example: 508-555-1234', max_length=32),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_phone_link',
            field=models.CharField(blank=True, help_text='Phone in tel: format. Example: 15085551234', max_length=32),
        ),
    ]
