# Generated by Django 5.2.8 on 2025-11-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_sitesettings_lead_recipients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address_line1',
            field=models.CharField(blank=True, help_text='Office street address line 1.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_line2',
            field=models.CharField(blank=True, help_text='Office street address line 2 (optional).', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='city',
            field=models.CharField(blank=True, help_text='Office city.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Office ZIP / postal code.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='state',
            field=models.CharField(blank=True, help_text='Office state.', max_length=100),
        ),
    ]
