# Generated by Django 5.2.8 on 2025-11-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_sitesettings_address_line1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short label for the announcement (internal or small heading).', max_length=200)),
                ('message', models.TextField(help_text='Main announcement text shown in the bar.')),
                ('button_label', models.CharField(blank=True, help_text="Optional button label. Example: 'Learn More' or 'View Details'.", max_length=100)),
                ('button_url', models.URLField(blank=True, help_text='Optional URL for the button. Can be an internal or external link.')),
                ('is_active', models.BooleanField(default=False, help_text='If checked, this announcement may be shown on the site.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ('-updated',),
            },
        ),
    ]
