# Generated by Django 5.2.8 on 2025-11-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='communities_intro',
            field=models.TextField(blank=True, help_text='Intro text shown at the top of the Communities page.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homes_intro',
            field=models.TextField(blank=True, help_text='Intro text shown at the top of the Available Homes page.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='plans_intro',
            field=models.TextField(blank=True, help_text='Intro text shown at the top of the Floor Plans page.'),
        ),
    ]
