# Generated by Django 5.2.8 on 2025-11-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_sitesettings_communities_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_background',
            field=models.ImageField(blank=True, help_text='Homepage hero background image.', null=True, upload_to='hero/'),
        ),
    ]
