# Generated by Django 5.2.8 on 2025-11-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_sitesettings_hero_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_phone_label',
            field=models.CharField(blank=True, default='Ask a Pro', help_text='Small label above the phone number.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_phone_link',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
