# Generated by Django 5.2.8 on 2025-11-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_sitesettings_cta_phone_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_background',
            field=models.ImageField(blank=True, help_text='Homepage hero background image.', null=True, upload_to='site/hero/'),
        ),
    ]
