# Generated by Django 5.2.8 on 2025-11-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_sitesettings_hero_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_phone_label',
            field=models.CharField(blank=True, help_text="Label for the phone button. Example: 'Call Us'", max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_phone',
            field=models.CharField(blank=True, help_text='Main phone number (for header / CTA). Example: 508-555-1234', max_length=32),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_phone_link',
            field=models.CharField(blank=True, help_text='Phone in tel: format. Example: 15085551234', max_length=32),
        ),
    ]
