# Generated by Django 5.2.8 on 2025-11-11 19:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('slug', models.SlugField(help_text='URL slug', max_length=160, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('beds', models.PositiveSmallIntegerField(default=3)),
                ('baths', models.DecimalField(decimal_places=1, default=Decimal('2.0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('garage_cars', models.PositiveSmallIntegerField(default=2)),
                ('sq_ft_min', models.PositiveIntegerField(blank=True, null=True)),
                ('sq_ft_max', models.PositiveIntegerField(blank=True, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional from-price', max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('brochure_pdf', models.FileField(blank=True, upload_to='plans/brochures/%Y/%m/%d/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlanSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('slug', models.SlugField(help_text='URL slug', max_length=160, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('coming', 'Coming Soon'), ('active', 'Active'), ('closing', 'Closing Out'), ('sold_out', 'Sold Out')], default='active', max_length=20)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('county', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(default='MA', max_length=2)),
                ('school_district', models.CharField(blank=True, max_length=160)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='communities', to='catalog.amenity')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AvailableHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('slug', models.SlugField(help_text='URL slug', max_length=160, unique=True)),
                ('address_1', models.CharField(blank=True, max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, help_text='US state code, e.g. MA', max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('lot_number', models.CharField(blank=True, max_length=50)),
                ('mls_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('uc', 'Under Construction'), ('pending', 'Pending'), ('sold', 'Sold'), ('coming', 'Coming Soon')], default='active', max_length=20)),
                ('ready_date', models.DateField(blank=True, help_text='Target completion/ready date', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('beds', models.PositiveSmallIntegerField(default=3)),
                ('baths', models.DecimalField(decimal_places=1, default=Decimal('2.0'), max_digits=3)),
                ('garage_cars', models.PositiveSmallIntegerField(default=2)),
                ('sq_ft', models.PositiveIntegerField(blank=True, null=True)),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homes', to='catalog.community')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homes', to='catalog.floorplan')),
            ],
            options={
                'ordering': ['community__name', 'lot_number', 'address_1'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('category', models.CharField(choices=[('exterior', 'Exterior'), ('kitchen', 'Kitchens'), ('bathroom', 'Bathrooms'), ('fireplace', 'Fireplaces'), ('stairs', 'Stairs'), ('other', 'Other Rooms')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('linked_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('linked_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('global', 'Site-wide form'), ('community', 'Community page'), ('plan', 'Plan page'), ('home', 'Available home page'), ('other', 'Other')], default='global', max_length=30)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('page_url', models.URLField(blank=True, help_text='Page URL where the lead was submitted')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('base_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.community')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.floorplan')),
            ],
            options={
                'verbose_name_plural': 'Plan availability',
            },
        ),
        migrations.AddField(
            model_name='floorplan',
            name='available_in',
            field=models.ManyToManyField(blank=True, related_name='available_plans', through='catalog.PlanAvailability', to='catalog.community'),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='catalog.planseries'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['status'], name='catalog_com_status_535696_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['city', 'state'], name='catalog_com_city_5f1531_idx'),
        ),
        migrations.AddIndex(
            model_name='availablehome',
            index=models.Index(fields=['status'], name='catalog_ava_status_acf395_idx'),
        ),
        migrations.AddIndex(
            model_name='availablehome',
            index=models.Index(fields=['community', 'status'], name='catalog_ava_communi_2047a9_idx'),
        ),
        migrations.AddIndex(
            model_name='availablehome',
            index=models.Index(fields=['beds', 'baths'], name='catalog_ava_beds_4b07a6_idx'),
        ),
        migrations.AddIndex(
            model_name='availablehome',
            index=models.Index(fields=['price'], name='catalog_ava_price_7cc0bd_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='catalog_lea_created_afb91d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source'], name='catalog_lea_source_c50362_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planavailability',
            unique_together={('plan', 'community')},
        ),
        migrations.AddIndex(
            model_name='floorplan',
            index=models.Index(fields=['beds', 'baths'], name='catalog_flo_beds_1cf6d3_idx'),
        ),
        migrations.AddIndex(
            model_name='floorplan',
            index=models.Index(fields=['sq_ft_min', 'sq_ft_max'], name='catalog_flo_sq_ft_m_ab4984_idx'),
        ),
    ]
