# Generated by Django 5.2.8 on 2025-11-13 13:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='linked_content_type',
        ),
        migrations.AlterUniqueTogether(
            name='planavailability',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='planavailability',
            name='community',
        ),
        migrations.RemoveField(
            model_name='planavailability',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='available_in',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='series',
        ),
        migrations.AlterModelOptions(
            name='amenity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='availablehome',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='floorplan',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('sort_order', 'id')},
        ),
        migrations.RemoveIndex(
            model_name='availablehome',
            name='catalog_ava_status_acf395_idx',
        ),
        migrations.RemoveIndex(
            model_name='availablehome',
            name='catalog_ava_communi_2047a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='availablehome',
            name='catalog_ava_beds_4b07a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='availablehome',
            name='catalog_ava_price_7cc0bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='community',
            name='catalog_com_status_535696_idx',
        ),
        migrations.RemoveIndex(
            model_name='community',
            name='catalog_com_city_5f1531_idx',
        ),
        migrations.RemoveIndex(
            model_name='floorplan',
            name='catalog_flo_beds_1cf6d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='floorplan',
            name='catalog_flo_sq_ft_m_ab4984_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='catalog_lea_created_afb91d_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='catalog_lea_source_c50362_idx',
        ),
        migrations.RemoveField(
            model_name='availablehome',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='availablehome',
            name='garage_cars',
        ),
        migrations.RemoveField(
            model_name='availablehome',
            name='lot_number',
        ),
        migrations.RemoveField(
            model_name='availablehome',
            name='mls_number',
        ),
        migrations.RemoveField(
            model_name='availablehome',
            name='ready_date',
        ),
        migrations.RemoveField(
            model_name='availablehome',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='availablehome',
            name='year_built',
        ),
        migrations.RemoveField(
            model_name='community',
            name='county',
        ),
        migrations.RemoveField(
            model_name='community',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='community',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='community',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='community',
            name='school_district',
        ),
        migrations.RemoveField(
            model_name='community',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='brochure_pdf',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='garage_cars',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='target_content_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='target_object_id',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='order',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='availablehome',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availablehome',
            name='featured_rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='availablehome',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='availablehome',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='community',
            name='available_plans',
            field=models.ManyToManyField(blank=True, related_name='available_in', to='catalog.floorplan'),
        ),
        migrations.AddField(
            model_name='community',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='featured_rank',
            field=models.PositiveIntegerField(default=0, help_text='Lower shows first among featured'),
        ),
        migrations.AddField(
            model_name='community',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='community',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floorplan',
            name='featured_rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='availablehome',
            name='address_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='availablehome',
            name='address_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='availablehome',
            name='baths',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='availablehome',
            name='beds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='availablehome',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homes', to='catalog.community'),
        ),
        migrations.AlterField(
            model_name='availablehome',
            name='postal_code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='availablehome',
            name='slug',
            field=models.SlugField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='availablehome',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='availablehome',
            name='status',
            field=models.CharField(choices=[('coming', 'Coming Soon'), ('uc', 'Under Construction'), ('active', 'Active'), ('pending', 'Pending'), ('sold', 'Sold')], default='coming', max_length=20),
        ),
        migrations.AlterField(
            model_name='community',
            name='slug',
            field=models.SlugField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='community',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('coming', 'Coming Soon'), ('closing', 'Closing Out'), ('sold_out', 'Sold Out')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='baths',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='beds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='slug',
            field=models.SlugField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='page_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('site', 'Website'), ('plan', 'Plan Page'), ('community', 'Community Page'), ('home', 'Home Page')], default='site', max_length=20),
        ),
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='GalleryItem',
        ),
        migrations.DeleteModel(
            name='PlanAvailability',
        ),
        migrations.DeleteModel(
            name='PlanSeries',
        ),
    ]
