# Generated by Django 6.0.1 on 2026-03-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='info_sections',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
