# Generated by Django 6.0.1 on 2026-03-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_community_share_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='share_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='communities/share_banners/'),
        ),
    ]
