# Generated by Django 5.2.8 on 2026-03-27 13:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_plan_home_share_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CombinedClientSharePage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("share_banner_image", models.ImageField(blank=True, null=True, upload_to="combined_shares/share_banners/")),
                ("share_enabled", models.BooleanField(default=False)),
                ("share_token", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("section_one", models.CharField(choices=[("home", "Available Home"), ("plan", "Floor Plan"), ("community", "Community")], default="home", max_length=20)),
                ("section_two", models.CharField(choices=[("home", "Available Home"), ("plan", "Floor Plan"), ("community", "Community")], default="plan", max_length=20)),
                ("section_three", models.CharField(choices=[("home", "Available Home"), ("plan", "Floor Plan"), ("community", "Community")], default="community", max_length=20)),
                ("community", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="combined_share_pages", to="catalog.community")),
                ("home", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="combined_share_pages", to="catalog.availablehome")),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="combined_share_pages", to="catalog.floorplan")),
            ],
            options={
                "ordering": ("title",),
            },
        ),
    ]
